version: '3.9'
services:
  readme.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "readme.notify.fakesmtp"
    hostname: "readme.notify.fakesmtp"
    ports:
      - "8025:8025"
      - "1083:8080"

  readme.notify.rabbitmq:
      image: rabbitmq:3.11-management
      container_name: readme.notify.rabbitmq

      ports:
        - '1088:15672'
        - '5672:5672'

      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

      healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 5s
        retries: 5

  readme.notify.mongodb:
    image: mongo:4.4
    restart: always
    container_name: readme.notify.mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.notify.mongodb:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.notify.mongodb.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme.notify.mongodb.ui
    ports:
      - 8086:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.notify.mongodb:27017/

volumes:
  readme.notify.mongodb:

# docker compose --file ./apps/notify/docker-compose.dev.yml --project-name "readme-notify" up -d
# docker compose --file ./apps/notify/docker-compose.dev.yml --env-file ./apps/notify/notify.env --project-name "readme-notify" up -d
# docker compose --file ./apps/notify/docker-compose.dev.yml --project-name "readme-notify" down -v
# docker system prune -a
